CFLAGS += -I./arch/$(ARCH)/include/
CONSTANTS-$(CONFIG_DBGHELLO) += -DDBGHELLO

obj-1 += printk.o
obj-1 += console.o tty.o
obj-1 += string.o panic.o 
obj-1 += sysmem.o kalloc.o
obj-1 += param.o init.o
obj-1 += mm.o
obj-1 += irq.o
obj-1 += fault.o
obj-1 += timer.o
obj-1 += irqsource.o
obj-1 += cpu.o
